---
services:
  meal-planner:
    build: .
    depends_on:
      - postgres
      - redis
    restart: unless-stopped
    ports:
      - 3000:3000
    develop:
      watch:
        - action: rebuild
          path: ./pkg
        - action: rebuild
          path: ./cmd
        - action: sync
          path: ./static
          target: /root/static
        - action: rebuild
          path: ./docker-compose.yml
        - action: rebuild
          path: ./Dockerfile
    environment:
      DEBUG: true
      PORT: 3000
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: meal_planner
      POSTGRES_DB: meal_planner
      REDIS_ADDR: redis:6379

  redis:
    image: redis:alpine
    restart: unless-stopped
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - 6379
    volumes:
      - redis-data:/data

  postgres:
    image: postgres:16-alpine
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=meal_planner
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_DB=meal_planner

volumes:
  redis-data:
  postgres-data:
